name: Jekyll site CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      run: |
        git config user.name "ahmadaldadah"
        git config user.email "ahmadaldadah@users.noreply.github.com"
        mv _site ../_site
        cd ../_site
        rm -rf .git
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy Jekyll site to GitHub Pages"
        git push --force origin gh-pages
